### PR TITLE
Updated block, unset and SUMMARY

### PR DESCRIPTION
**Pull request by gltewalt**

### CODE REVIEW

**Comment by PeterWAWood** [comment]
I don't think this is the correct way to explain blocks:
"Blocks are the aggregate structures for values of all possible types. They are used to represent data or code that can be evaluated at any point in runtime."

A block should be explained in terms of series, which requires series to be explained first. A block is simply a series with no restriction on the type of values that can be referenced in it.

**Comment by greggirwin** [comment]
How about "Blocks are used to represent data or code that can be evaluated at any point in time. They are a type of [series](link to series doc) with no restriction on the type of values that can be referenced."

**Comment by gltewalt** [comment]
Edited with Greggs description.

**Comment by PeterWAWood** [comment]
"Because each page is for a specific type in this context, I don't know that we can explain series values first, but we need to make it easy to get to series docs from there."

The pages are not intended to be published individually, but included in "The Red User Guide". The date! page was special as Nenad wrote it specifically to introduce date!. It made sense to have separate files for each datatype as it reduces the chance of concurrent updates. All the datatype pages were planned to be published together in a similar fashion to Appendix 1 of the Rebol User Guide.

**Pull request merged**
