### PR TITLE
French translation of Red docs

### PR DESCRIPTION
**Pull request by Palaing**
Proposed translation of official docs, based on English version as of Sept. 19.
(commit 89a5e65134ec706064f0b68b27e1886318fe6888)

### CODE REVIEW

**Comment by greggirwin** [comment]
Thanks so much!

**Comment by Palaing** [comment]
just updated LANGS.adoc too ; not sure if/what else should be done to make it available online.

**Comment by greggirwin** [comment]
Merged it, but not seeing any change yet. @gltewalt, do you know if something else needs to be done to make it show up?

**Comment by gltewalt** [comment]
From what I can see, everything looks correct.

**Comment by greggirwin** [comment]
I see it now as well. Thanks for checking @gltewalt.

**Comment by x8x** [comment]
@greggirwin I'm not sure how wise it is to continue to use legacy GitBook, obviously they are/will focus on the new version. There is a recent issue about GitHub -> GitBook syncing opened 20 days ago https://github.com/GitbookIO/gitbook/issues/2184 , not much details on it.
I have forked docs repo and created a GitBook account to try to reproduce the problem but it's impossible to use legacy from new accounts.
If you don't have access to Red GitBook account then I'm afraid only @dockimbel can have a look at what the issue is. @dockimbel if you have set up an organisation on GitBook, maybe you can add me there and I can have a look.

**Pull request merged**
