### PR TITLE
Note about path! evaluating stored functions

### PR DESCRIPTION
**Pull request by gltewalt**

### CODE REVIEW

**Comment by 9214** [comment]
I'd rather add a more elaborate example and mentioned `pick`, `select` and `get-path!`s:
```red
>> foo: reduce ['a does ['b]]
== [a func []['b]]

>> foo/a
== b
>> foo/2
== b

>> :foo/a
== func []['b]
>> :foo/2
== func []['b]

>> select foo 'a
== func []['b]
>> pick foo 2
== func []['b]
```

**Comment by greggirwin** [comment]
@9214, `get-path!` has its own doc page, which is where we should note that, and `pick/select` probably don't belong on the ref page for `path!` either. What we could use, if you're up for it, is a page explaining access and evaluation options and behaviors. It's an important and nuanced subject that deserves good treatment.

**Comment by 9214** [comment]
@greggirwin I believe @meijeru already faithfully covered all these details in his spec.

**Comment by greggirwin** [comment]
@9214 so you're OK with the current change @gltewalt made? Just wanted to make sure there weren't any other tweaks before merging.

**Comment by 9214** [comment]
@greggirwin I'd also added an example with key selection, to avoid possible confusion, and (optionally) commented that it does not work with `op!` values (see https://github.com/red/red/issues/3482) yet.
```red
>> foo: reduce ['a does ['b]]
== [a func []['b]]

>> foo/a ; key
== b
>> foo/2 ; index
== b
```

**Comment by greggirwin** [comment]
@gltewalt please include the key example and a comment about op values not being evaluated. Can be a small addition to what you have now. e.g. "Paths are an active type and will evaluate stored functions, but not `op!` values."

**Comment by gltewalt** [comment]
According to Peter Wood per Nenads wishes, examples should be minimal and I probably have too many examples in my current doc versions.

**Pull request merged**
