### PR TITLE
Docs-cs: last changes translated

### PR DESCRIPTION
**Pull request by Tovim**
There is no need to merge  all 119 commits into red:master, only those, concerned with the cs/folder.

### CODE REVIEW

**Comment by greggirwin** [comment]
A PR with just the necessary commits, and no conflicts, would be great.

**Comment by Tovim** [comment]
> 
> 
> A PR with just the necessary commits, and no conflicts, would be great.

That exactly is my dream target. I am going to read something about Git as, I can see, I am unsufficiently competent. 
My appologies. Tovim

**Comment by greggirwin** [comment]
No apologies necessary. Git and I are not friends either. :^)

**Comment by greggirwin** [comment]
Thanks!

**Pull request merged**
