### PR TITLE
error! v1

### PR DESCRIPTION
**Pull request by gltewalt**

### CODE REVIEW

**Comment by greggirwin** [comment]
Says there are conflicts. Imagine you're on it, as I just happened to catch the PR right away. :^)

**Comment by gltewalt** [comment]
Seems ok now. I was bitten by git stash, I think.

**Comment by greggirwin** [comment]
Looks like some git patch lines made it into Summary now.

**Comment by gltewalt** [comment]
I’ll have to fix it tonight sometime.

**Pull request merged**
