### PR TITLE
FEAT: Parse documentation

### PR DESCRIPTION
**Pull request by 9214**
This is a preliminary draft of Parse reference documentation, covering its existing functionality and providing minimal examples for all the rules, which are grouped into sections according to their common use-cases.

Table at the bottom lists currently pending Parse-related issues. I advise to close or comment on each of them before merging this PR.

### CODE REVIEW

**Comment by bubnenkoff** [comment]
Thanks! I have some experience with parse, but example seems for me too complicated. Examples from `Helpin Red` much more simple

**Comment by 9214** [comment]
@bubnenkoff it's a reference documentation (information-oriented) for experienced developers, not a tutorial (learning-oriented) for newcomers, so your complaint and comparison entirely miss the point.

All examples are:
* self-contained (rely only on previously covered rules);
* authoritative (precise and to the point);
* exhaustive (cover most of the edge-cases, and, when possible, demonstrate conditions under which the rules fails, succeeds and advances the input);
* illustrative (serve as a recap of the core Parse principles and a described rule, all of which the reader is assumed to understand even without examples).

So, if you think some of the examples do not match the above criteria — I'll update them right away. Ultimately, this document acts as a reliable, descriptive source to which people can refer and from which information for other types of documentation (tutorials, cookbooks, and explanations) can be extracted.

**Comment by hiiamboris** [comment]
see my PM on gitter too, @9214

**Comment by greggirwin** [comment]
I'm going to merge this. Holding back docs for bugs doesn't make sense. The issues are noted, and we can do the same for open design issues.

**Comment by endo64** [comment]
Great document, I'm just not sure if using unicode chars is a good idea, they cannot be copied & pasted onto CLI console (on Windows at least).
I prefer keeping only one as an example.

**Pull request merged**
