### PR TITLE
Add Japanese documents

### PR DESCRIPTION
**Pull request by koba-yu**
I have finished translating the documents into Japanese. This is my first experience to make a pull request. So, if there is something wrong with this pull request, would you let me know please?

### CODE REVIEW

**Comment by greggirwin** [comment]
@koba-yu, thank you so much for this contribution! You PR looks good to me. The main problem people have is when they create conflicts, or have unrelated commits grouped together. You don't have either of those problems, so you should see this merged shortly I think.

**Comment by dockimbel** [comment]
@koba-yu Fantastic work, thank you so much! :100: :+1:

**Comment by AT-Aoi** [comment]
@koba-yu I find some problems in the `draw.adoc` and `vid.adoc`. The catalog is not complete and the content's format is strange.

**Comment by koba-yu** [comment]
@greggirwin @dockimbel Thank you for your reviewing and merging!

**Comment by koba-yu** [comment]
@AT-Aoi Thank you for your reviewing. I have found Japanese draw.adoc misses toclevels attribute(English version has that). I should modify this next time(maybe when I do next version Red document translation?).
However I can not find out the problem with vid.adoc. Could you clarify on which section or row number has the problem and how wrong it is?

**Comment by AT-Aoi** [comment]
@koba-yu 
The TOC is missing a lot, starting from `3.1. title`.
**JP:**
image
**EN:**
image

---

Like the `Layout` section, the whole section has become a code block. And the images don't show.
**JP:**
image
**EN:**
image

**Comment by koba-yu** [comment]
@AT-Aoi Thank you for your reply!
Hmmm.....It seems not broken on my browser...  
Could you tell me which OS and browser you use? Anyway, I try to find difference between English and Japanese documents and what is the cause...
On my browser

**Comment by AT-Aoi** [comment]
@koba-yu I am on win10 and using Vivaldi browser(blink engine).
I find that adding a blank line after [the "\*構文\*" in line 46](https://github.com/red/docs/blame/master/ja/vid.adoc#L46) brings back the `3.2. size` in TOC. I think it is the cause.

**Comment by geekyi** [comment]
@AT-Aoi works fine for me on chrome and vivaldi on win 10 64bit 1703:
```
Vivaldi | 1.10.867.42 (Stable channel) (32-bit)
Revision | 1c037b7399035b4209e72455256615e8972493aa
OS | Windows
JavaScript | V8 5.9.211.35
```
Did anything change? I'm looking at https://doc.red-lang.org/ja/vid.html

**Comment by AT-Aoi** [comment]
@geekyi 
Ah. I was looking at [the github's](https://github.com/red/docs/blob/master/ja/vid.adoc). Now I have checked gitbook. It is ok.

**Comment by koba-yu** [comment]
@AT-Aoi @geekyi 
Thank you four your checkings! So gitbook is ok but github preview is not. English version github preview is ok so it may be better Japanese preview is correct too. I will check it.
(AT-Aoi taught me adding a line makes it correct but I am not sure it needs grammatically. Do you know why? ) 
Anyway, thank you guys again!

**Comment by geekyi** [comment]
@koba-yu I think it's confusion of [level 1 headers](https://powerman.name/doc/asciidoc#_headers)
with [blocks](https://powerman.name/doc/asciidoc#_blocks), which both use `--`:

```asciidoc
Level 1
-------
Text.

.Optional Title
----
*Listing* Block

Use: code or file listings
----
```

Examples source blocks should probably be changed to have `.` instead of `*`:

```asciidoc
.*構文*
[source,red]
----
title <text>
```

Happens with plain text formats like markdown and asciidoc, as there is no delimiter for blocks.
Usually new line is used as block separator, so I usually use more new lines if problems occur

**Pull request merged**
